### ISSUE TITLE
Is it TCP or SSH checker?

### ISSUE THREAD

**Issue by iddq** [tommybutler/sshping#1]
Is it TCP or SSH checker?

**Comment by tommybutler** [comment]
SSH checker

**Comment by iddq** [comment]
No it is not. It only checks if the TCP port is open. it doesn't do any SSH negotiation or checking.

**Comment by tommybutler** [comment]
I'm sorry, I guess I did not understand your original question. Yes, this
is correct. It checks to make sure that the port is open. It does not
attempt to connect to the SSH service. For that you would need something
like Net::SSH
